### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [NishikawaYusaku/Chaos#63]
@NishikawaYusaku 
リリースお疲れ様でした。
下記に現状のフィードバックをあげたのでご確認ください。

## UI
- どのユーザーがvtuberの設定情報をいじっていいのかなどわかりにくいので、登録した人しか編集できないのか、みんなで編集できるのかなどの権限周りを明確にしてあげましょう。
- 新規登録への導線がヘッダー内の「設定」だとちょっとわかりにくいので、文言や導線周りを修正してみてください。

## 技術
- ルーティング周りはログイン、ログアウト関係以外はほぼresourcesベースで実装できるかと思うので、修正してください。
- コード内のコメント等でコードを消している部分は削除しておきましょう。
- 機能的にはまだ技術の強みをいかせていないので、マルチ検索などその他の機能はマストで実装しましょう

以上でございます。
上記内容をissueに落とし込んでいただいたら、
現状の残りのタスクを含めて、こちらのスレッドに再度実装完了のスケジュールを共有ください。
よろしくお願いいたします。

**Comment by NishikawaYusaku** [comment]
@kerochelo さん
お世話になります。
ご確認頂きましてありがとうございます。
それぞれを下記の通りissueに落とし込みました。
***
> どのユーザーがvtuberの設定情報をいじっていいのかなどわかりにくいので、登録した人しか編集できないのか、みんなで編集できるのかなどの権限周りを明確にしてあげましょう。

* #64

> 新規登録への導線がヘッダー内の「設定」だとちょっとわかりにくいので、文言や導線周りを修正してみてください。

* #65

> ルーティング周りはログイン、ログアウト関係以外はほぼresourcesベースで実装できるかと思うので、修正してください。

* #66

> コード内のコメント等でコードを消している部分は削除しておきましょう。

* #67

> 機能的にはまだ技術の強みをいかせていないので、マルチ検索などその他の機能はマストで実装しましょう

→ マルチ検索、通知機能、レコメンド機能を予定しております。
* マルチ検索：　#17 
* 通知機能：　#18 #19 
* レコメンド機能：　#43 #16 
***
> 上記内容をissueに落とし込んでいただいたら、
現状の残りのタスクを含めて、こちらのスレッドに再度実装完了のスケジュールを共有ください。

こちらはMVPリリース段階はまだ途中で、頂いたフィードバック内容を改修・実装後に完了ということでしょうか？

**Comment by kerochelo** [comment]
@NishikawaYusaku 
MVPリリースは一旦完了です！
そのため今回のフィードバック分のissueと残り機能のissueを含めて、再度本リリースまでのスケジュールを共有いただきたい形です！

**Comment by NishikawaYusaku** [comment]
@kerochelo さん
承知いたしました、ありがとうございます。
1ヶ月後の3/1（金）とさせていただきたく思います。

**Comment by kerochelo** [comment]
承知しました！引き続き頑張っていきましょう :+1:
